import { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { Menu, X, ShoppingCart, Zap, Wrench, Hammer, HousePlug, HardHat } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useCart } from "../context/CartContext";

export const Header = () => {
  const [isScrolled,setIsScrolled]=useState(false), [isMobileMenuOpen,setIsMobileMenuOpen]=useState(false), [showServicesMenu,setShowServicesMenu]=useState(false);
  const location=useLocation(); const { count }=useCart();
  useEffect(()=>{const h=()=>setIsScrolled(window.scrollY>20);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);
  useEffect(()=>setIsMobileMenuOpen(false),[location]);
  const navLinks=[{name:"Home",path:"/"},{name:"Products",path:"/products"},{name:"Services",submenu:[{name:"Solar Installation",path:"/services/solar",icon:Zap},{name:"Electrical",path:"/services/electrical",icon:HousePlug},{name:"Carpentry",path:"/services/carpentry",icon:Hammer},{name:"Plumbing",path:"/services/plumbing",icon:Wrench},{name:"Steel Work",path:"/services/steelwork",icon:HardHat}]},{name:"About",path:"/about"},{name:"Contact",path:"/contact"}];
  return <header className={`fixed top-0 left-0 right-0 z-50 transition-colors duration-300 ${isScrolled?"header-scrolled":"bg-transparent"}`} data-testid="main-header"><div className="max-w-7xl mx-auto px-6 md:px-12"><nav className="flex items-center justify-between h-20 md:h-26">
    <Link to="/" className="flex items-center gap-4 select-none"><img src="/dark-logo.png" alt="Jonesaica Infrastructure Solutions" className="h-22 md:h-24 w-auto object-contain"/><div className="leading-tight"><span className="block font-heading font-bold text-lg md:text-xl text-royal-300 tracking-tight">JONESAICA</span><span className="block text-gold-400 text-[10px] md:text-xs font-semibold tracking-widest uppercase">Infrastructure</span><span className="block text-gold-300 text-[10px] md:text-xs font-medium tracking-widest uppercase">Solutions</span></div></Link>
    <div className="hidden lg:flex items-center gap-8">{navLinks.map(link=>link.submenu?<div key={link.name} className="relative" onMouseEnter={()=>setShowServicesMenu(true)} onMouseLeave={()=>setShowServicesMenu(false)}><button className="text-royal-300 hover:text-gold-400 font-medium">{link.name}</button><AnimatePresence>{showServicesMenu&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}} className="absolute top-full left-0 mt-2 w-56 glass-card py-2">{link.submenu.map(s=><Link key={s.path} to={s.path} className="flex items-center gap-3 px-4 py-3 text-royal-300 hover:text-gold-400"><s.icon size={18}/>{s.name}</Link>)}</motion.div>}</AnimatePresence></div>:<Link key={link.path} to={link.path} className={`font-medium ${location.pathname===link.path?"text-gold-400":"text-royal-300 hover:text-white"}`}>{link.name}</Link>)}</div>
    <div className="flex items-center gap-4"><Link to="/quote" className="hidden sm:block btn-gold px-6 py-3 text-sm font-bold">Get Quote</Link><Link to="/cart" className="relative p-2 text-royal-300 hover:text-gold-400" aria-label="Shopping cart"><ShoppingCart size={24}/>{count>0&&<span className="absolute -top-1 -right-1 bg-gold-500 text-royal-950 text-xs w-5 h-5 rounded-full flex items-center justify-center font-bold">{count}</span>}</Link><button className="lg:hidden p-2 text-royal-300 hover:text-white" onClick={()=>setIsMobileMenuOpen(!isMobileMenuOpen)}>{isMobileMenuOpen?<X size={24}/>:<Menu size={24}/>}</button></div>
  </nav><AnimatePresence>{isMobileMenuOpen&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="lg:hidden glass-card mb-4 overflow-hidden"><div className="py-4">{navLinks.map(link=>link.submenu?<div key={link.name} className="px-4 py-2"><p className="text-royal-400 text-sm font-medium mb-2">{link.name}</p>{link.submenu.map(s=><Link key={s.path} to={s.path} className="flex items-center gap-3 px-4 py-2 text-royal-300 hover:text-gold-400"><s.icon size={16}/>{s.name}</Link>)}</div>:<Link key={link.path} to={link.path} className="block px-4 py-3 font-medium text-royal-300">{link.name}</Link>)}<div className="px-4 pt-4 flex gap-3"><Link to="/quote" className="flex-1 btn-gold px-4 py-3 text-center">Get Quote</Link><Link to="/cart" className="btn-outline px-4 py-3 flex items-center gap-2"><ShoppingCart size={18}/>Cart ({count})</Link></div></div></motion.div>}</AnimatePresence></div></header>;
};
